todolist/list/urls.py
from django.conf.urls import url
from  .import views

app_name='mysite'

urlpatterns=[
    url('priority/(?P<priorityInput>[^/]+)', views.priority, name='priority'),
    url('category/(?P<categoryInput>[^/]+)', views.category, name='category'),
    url('detail/(?P<detail_id>[0-9]+)', views.detail, name='detail'),
    url('cross_off/(?P<list_id>[0-9]+)', views.cross_off, name='cross_off'),
    url('uncross/(?P<list_id>[0-9]+)', views.uncross, name='uncross'),
    url('search/', views.search, name='search'),
    url('del/(?P<delete_id>[0-9]+)', views.delete, name='delete'),
    url('update/(?P<update_id>[0-9]+)', views.update, name='update'),
    url('create/', views.create, name='create'),
    url('',views.list, name='index'),
]

todolist/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    
    path('list/',include ('list.urls', namespace="list")),
    path('',views.index, name='home'),
    path('admin/', admin.site.urls),
    
    
]

todolist/list/models.py
from django.db import models

class List(models.Model):
    item = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)
    category = models.CharField(max_length=50, default='')
    priority = models.CharField(max_length=50, default='')
    subitem = models.TextField(max_length=300, default='', blank=True)


    def __str__(self):
        return self.item + ', ' + str(self.completed)

todolist/list/forms.py
from django import forms
from .models import List

class ListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ["item", "completed", "category", "priority", "subitem"]

todolist/list/views.py
from django.shortcuts import render, redirect
from .models import List
from .forms import ListForm
from django.db.models import Q
from django.contrib import messages

def detail(request, detail_id):
    detail_item = List.objects.get(id=detail_id)  

    context = {
        'Title' : 'Detail', 
        'detail_item' : detail_item,
    }
    return render (request, 'list/detail.html', context)

def priority(request, priorityInput):
    all_items = List.objects.filter(priority=priorityInput)
    priority_menu = List.objects.values('priority').distinct().exclude(priority=priorityInput)
    priority_judul=priorityInput
    category_menu = List.objects.values('category').distinct()

    context = {
        'Title' : 'Priority',
        'all_items' : all_items,
        'priority_menu' : priority_menu,
        'priority_judul' :priority_judul,
        'category_menu' : category_menu,
    }
    return render (request, 'list/priority.html',context)


def category(request, categoryInput):
    all_items = List.objects.filter(category=categoryInput)
    category_menu = List.objects.values('category').distinct().exclude(category=categoryInput);
    # print(category_list)
    category_judul = categoryInput
    priority_menu = List.objects.values('priority').distinct()

    context = {
        'Title' : 'Category',
        'all_items' : all_items,
        'category_menu': category_menu,
        'category_judul': category_judul,
        'priority_menu': priority_menu,
        

    }
    return render (request, 'list/category.html',context)

def cross_off (request,list_id):
    item= List.objects.get(pk=list_id)
    item.completed = True
    item.save()
    messages.success(request,('item changed  "Done"'))
    return redirect('list:index')

def uncross(request, list_id):
    item= List.objects.get(pk=list_id)
    item.completed = False
    item.save()
    messages.success(request,('item changed  "Not Done"'))
    return redirect('list:index')

def search(request):
    queryList = List.objects.all()
    queryCari = request.GET.get('kolomCari')

    if queryCari !='' and queryCari is not None :
        queryList = queryList.filter(Q(item__icontains = queryCari)| Q(category__icontains=queryCari)|Q(priority__icontains=queryCari)|Q(completed__icontains=queryCari))

    context = {
        'Title' : 'Search',
        'queryset' : queryList,
        }
    return render(request, 'list/search.html', context)

def delete(request, delete_id):
        List.objects.filter(id=delete_id).delete()
        messages.success(request,('Элемент был удален..!'))
        return redirect('list:create')

def update(request, update_id):
    item_update = List.objects.get(id=update_id)
    data = {
        'item' : item_update.item,
        'completed' : item_update.completed,
    }

    item_form = ListForm(request.POST or None, initial = data, instance = item_update)

    if request.method == 'POST' :
        if item_form.is_valid():
            item_form.save()
            messages.success(request,('элемент был отредактирован..!'))
        return redirect ('list:create')

    context = {
        'Title':'Update',
        "item_form" : item_form,
    }
    return render (request, 'list/update.html', context)

def create(request):
    all_items = List.objects.all()
    item_form = ListForm(request.POST or None)

    if request.method == 'POST' :
        if item_form.is_valid():
            item_form.save()
            messages.success(request,('данные добавлены в список!'))
            return redirect ('list/create.html')

    context = {
        "Title" : 'Create',
        'all_items' : all_items,
        "item_form" : item_form,
    }
    return render (request, 'list/create.html', context)

def list(request):
    all_items = List.objects.all() 

    category_menu=List.objects.values('category').distinct()
    # print(category_menu)

    priority_menu = List.objects.values('priority').distinct()
    # print(priority_menu_list)

    context = {
        'Title' : 'List',
        'all_items' : all_items,
        'category_menu' : category_menu,
        'priority_menu' : priority_menu,

    }
    return render (request, 'list/index.html', context)

todolist/mysite/views.py
from django.shortcuts import render
import requests
import json
from datetime import datetime, timedelta

def index(request):
    url = "https://api.covid19api.com/summary"
    # A summary of new and total cases per country updated daily.
    payload = {}
    headers= {}
    response = requests.request("GET", url, headers=headers, data = payload)

    data=response.json()
    datanegara = data['Countries']
    rus=datanegara[140]
    case2 = []
    result2 = {}
    result2['Country'] = rus['Country']
    result2['CountryCode'] = rus['CountryCode']
    result2['NewConfirmed'] = rus['NewConfirmed']
    result2['TotalConfirmed'] = rus['TotalConfirmed']
    result2['NewDeaths'] = rus['NewDeaths']
    result2['TotalDeaths'] = rus['TotalDeaths']
    result2['NewRecovered'] = rus['NewRecovered']
    result2['NewTotalRecoveredConfirmed'] = rus['TotalRecovered']
    result2['Date'] = rus['Date']
    case2.append(result2)

    update = datetime.now()-timedelta(days=1)

    response2= requests.get("https://api.apify.com/v2/key-value-stores/1brJ0NLbQaJKPTWMO/records/LATEST?disableRedirect=true")

    datarusia= response2.json()
    infectedByRegion=(datarusia['infectedByRegion'])
    tomsk = (infectedByRegion[32])
    case3 = []
    result3 = {}
    result3['region'] = tomsk['region']
    result3['isoCode'] = tomsk['isoCode']
    result3['infected'] = tomsk['infected']
    result3['recovered'] = tomsk['recovered']
    result3['deceased'] = tomsk['deceased']
    case3.append(result3)  

    case4 =[]
    for reg in infectedByRegion:
        result4={}
        result4['region'] = reg['region']
        result4['infected'] = reg['infected']
        result4['recovered'] = reg['recovered'] 
        result4['deceased'] = reg['deceased']
        case4.append(result4)


    context = {
        'Title' : 'Home',
        'case2' : case2,
        'case3' : case3,
        'case4': case4,
        'update' : update,
    }
    return render(request,'index.html', context)

todolist/list/templates/list/category.html
{% extends 'base.html' %}

{% block title %}
  {{Title}}
{% endblock title %}


{% block content %}
  
<!-- alert mesaage -->
<div class="col-lg-12">
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-warning alert-dismissable" role="alert">
    <button class="close" data-dismiss='alert'>
        <small><sup>x</sup></small>
        </button>
        {{message}}
    </div>
  {% endfor %}
{% endif %}
</div>
<!-- end alert mesaage -->

 <!-- left colomn -->
 <div class="col-sm-3 mb-5 pt-4">
  <div class="list-group mt-1">
    <span class="list-group-item active">
        Category :
    </span>
    <a href="{% url 'list:index' %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"> All Category </a>

    {% for category_list_menu in category_menu %}

   <a href="{% url 'list:category' categoryInput=category_list_menu.category %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"> {{category_list_menu.category}} </a>
   {% endfor %}
  </div>
  
  <div class="list-group mt-1">
    <span class="list-group-item active">
        Priority :
    </span>
    
    {% for priority_list_menu in priority_menu %}
    <a href="{% url 'list:priority' priorityInput=priority_list_menu.priority %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"> {{priority_list_menu.priority}} </a>
   {% endfor %}
  </div>
 </div>
  <!-- end left colomn -->
  

   <!-- right colomn -->
   <div class="col-sm-9">
<!-- List do -->
<div class="container pt-4">
        <table class="table table-striped table-hover table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">No</th>
            <th scope="col">items</th>
            <th scope="col">completed</th>
          </tr>
        </thead>
        <tbody>
            <div class="alert alert-primary" role="alert">
                Category : {{category_judul}}
              </div>
          {% for things in all_items %} 
            {% if things.completed %}
                <tr class="table-success">
                  <th scope="row">{{forloop.counter}}</th>
                  <td><a href="{% url 'list:detail' things.id  %}"><s>{{things.item}}</s></a></td>
                  <td><a href="{% url 'list:uncross' things.id  %}">сделано</a></td>
                </tr>
              {% else %}
                <tr>
                  <th scope="row">{{forloop.counter}}</th>
                  <td> <a href="{% url 'list:detail' things.id  %}">{{things.item}}</a> </td>
                  <td><a href="{% url 'list:cross_off' things.id  %}">не сделано</a></td>
                </tr>
              {% endif %}

          {% endfor %}
        </tbody>
       
      </table>
      
    </div>
     
<!-- end list do -->
</div>
<!--  end right colomn -->

{% endblock content %}





    

todolist/list/templates/list/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{Title}}
{% endblock title %}
    {{Title}}

{% block content %}
<div class="container pt-4">
    <div>
       <!-- alert message -->
       {% if messages %}
           {% for message in messages %}
           <div class="alert alert-warning alert-dismissable" role="alert">
            <button class="close" data-dismiss='alert'>
                <small><sup>x</sup></small>
               </button>
               {{message}}
           </div>
           {% endfor %}
       {% endif %}
       <!--  end alert message -->
           
    <h4>   Добавить новую деятельность : </h4>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{item_form}}
        </table>
        <button type="submit" class="btn btn-primary">Save</button>
        <hr>
    </div>

    <div class="container pt-5">
        <table id ="example" class="table table-striped table-hover table-sm">
          <thead class="thead-dark">
            <tr>
              <th scope="col">No</th>
              <th scope="col">items</th>
              <th scope="col">completed</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for things in all_items %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td> {{things.item}} </td>
              <td>{{things.completed}}</td>
              <td>
                <a href="{% url 'list:update' things.id %}"><button type="button" class="btn btn-outline-info">Edit</button></a>

                <a href="{% url 'list:delete' things.id %}" onclick="return confirm('вы уверены в удалении??')"><button type="button" class="btn btn-outline-danger">Del</button></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
</div>             
{% endblock content %}
    

todolist/list/templates/list/detail.html
{% extends 'base.html' %}

{% block title %}
{{Title}}
{% endblock title %}
    

{% block content %}
<div class=" container  pt-4">

    {% if detail_item.completed %}
        <div class="card text-center ">
            <div class="text-white card-header bg-primary">
            Priority :  {{detail_item.priority}}
            </div>
            <div class="card-body">
            <h5 class="card-title">{{detail_item.item}}</h5>
            <p class="card-text">{{detail_item.subitem}}</p>
            <a href="{% url 'list:uncross' detail_item.id  %}" class="btn btn-primary">Сделано</a>
            </div>
            <div class="card-footer text-muted-white bg-primary text-white">
            category :  {{detail_item.category}}
            </div>
        </div>
    {% else %}
        <div class="card text-center ">
            <div class=" card-header">
            Priority :  {{detail_item.priority}}
            </div>
            <div class="card-body">
            <h5 class="card-title">{{detail_item.item}}</h5>
            <p class="card-text">{{detail_item.subitem}}</p>
            <a href="{% url 'list:cross_off' detail_item.id  %}" class="btn btn-secondary">Не Сделано</a>
            </div>
            <div class="card-footer text-muted">
            category :  {{detail_item.category}}
            </div>
        </div>
    {% endif %}
    <div class= 'pt-4'>
     <a href="{% url 'list:index' %} " class="btn btn-info">Back</a>
    </div>
</div>
{% endblock content %}
    

todolist/list/templates/list/index.html
{% extends 'base.html' %}
{% block title %}
  {{Title}}
{% endblock title %}
{% block content %}
<!-- alert mesaage -->
<div class="col-lg-12">
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-warning alert-dismissable" role="alert">
    <button class="close" data-dismiss='alert'>
        <small><sup>x</sup></small>
        </button>
        {{message}}
    </div>
  {% endfor %}
{% endif %}
</div>
<!-- end alert mesaage -->

 <!-- left colomn -->
 <div class="col-sm-3 mb-5 pt-4">
  <div class="list-group mt-1">
    <span class="list-group-item active">
        Category :
    </span>
    {% for category_list_menu in category_menu %}
   <a href="{% url 'list:category' categoryInput=category_list_menu.category %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"> {{category_list_menu.category}} </a>
   {% endfor %}
  </div>
  
  <div class="list-group mt-1">
    <span class="list-group-item active">
        Priority :
    </span>
    
    {% for priority_list_menu in priority_menu %}
    <a href="{% url 'list:priority' priorityInput=priority_list_menu.priority %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"> {{priority_list_menu.priority}} </a>
   {% endfor %}
  </div>
 </div>
  <!-- end left colomn -->
  

   <!-- right colomn -->
   <div class="col-sm-9">
<!-- List do -->
<div class="container pt-4">
      <table class="table table-striped table-hover table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">No</th>
            <th scope="col">items</th>
            <th scope="col">completed</th>
          </tr>
        </thead>
        <tbody>
          {% for things in all_items %}
          
            {% if things.completed %}
                <tr class="table-success">
                  <th scope="row">{{forloop.counter}}</th>
                  <td><a href="{% url 'list:detail' things.id  %}"><s>{{things.item}}</s></a></td>
                  <td><a href="{% url 'list:uncross' things.id  %}">сделано</a></td>
                </tr>
              {% else %}
                <tr>
                  <th scope="row">{{forloop.counter}}</th>
                  <td> <a href="{% url 'list:detail' things.id  %}">{{things.item}}</a> </td>
                  <td><a href="{% url 'list:cross_off' things.id  %}">не сделано</a></td>
                </tr>
              {% endif %}

          {% endfor %}
        </tbody>
       
      </table>
      
    </div>
     
<!-- end list do -->
</div>
<!--  end right colomn -->

{% endblock content %}

todolist/list/templates/list/priority.html
{% extends 'base.html' %}

{% block title %}
  {{Title}}
{% endblock title %}


{% block content %}
  
<!-- alert mesaage -->
<div class="col-lg-12">
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-warning alert-dismissable" role="alert">
    <button class="close" data-dismiss='alert'>
        <small><sup>x</sup></small>
        </button>
        {{message}}
    </div>
  {% endfor %}
{% endif %}
</div>
<!-- end alert mesaage -->

 <!-- left colomn -->
 <div class="col-sm-3 mb-5 pt-4">
  <div class="list-group mt-1">
    <span class="list-group-item active">
        Category :
    </span>
    {% for category_list_menu in category_menu %}
   <a href="{% url 'list:category' categoryInput=category_list_menu.category %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"> {{category_list_menu.category}} </a>
   {% endfor %}
  </div>
  
  <div class="list-group mt-1">
    <span class="list-group-item active">
        Priority :
    </span>
    <a href="{% url 'list:index' %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"> All Priority </a>
    {% for priority_list_menu in priority_menu %}
    <a href="{% url 'list:priority' priorityInput=priority_list_menu.priority %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"> {{priority_list_menu.priority}} </a>
   {% endfor %}
  </div>
 </div>
  <!-- end left colomn -->
  

   <!-- right colomn -->
   <div class="col-sm-9">
<!-- List do -->
<div class="container pt-4">
        <table class="table table-striped table-hover table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">No</th>
            <th scope="col">items</th>
            <th scope="col">completed</th>
          </tr>
        </thead>
        <tbody>
            <div class="alert alert-primary" role="alert">
                Priority : {{priority_judul}}
              </div>
          {% for things in all_items %} 
            {% if things.completed %}
                <tr class="table-success">
                  <th scope="row">{{forloop.counter}}</th>
                  <td><a href="{% url 'list:detail' things.id  %}"><s>{{things.item}}</s></a></td>
                  <td><a href="{% url 'list:uncross' things.id  %}">сделано</a></td>
                </tr>
              {% else %}
                <tr>
                  <th scope="row">{{forloop.counter}}</th>
                  <td> <a href="{% url 'list:detail' things.id  %}">{{things.item}}</a> </td>
                  <td><a href="{% url 'list:cross_off' things.id  %}">не сделано</a></td>
                </tr>
              {% endif %}

          {% endfor %}
        </tbody>
       
      </table>
      
    </div>
     
<!-- end list do -->
</div>
<!--  end right colomn -->

{% endblock content %}





    

todolist/list/templates/list/search.html
{% extends 'base.html' %}

{% block title %}
  {{Title}}
{% endblock title %}


{% block content %}

<div class="container pt-4">
      <table class="table table-striped table-hover table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">No</th>
            <th scope="col">items</th>
            <th scope="col">category</th>
            <th scope="col">priority</th>
            <th scope="col">completed</th>
            
          </tr>
        </thead>
        <tbody>
          {% for search in queryset %}
            {% if search.completed %}
              <tr class=table-success>
                <th scope="row">{{forloop.counter}}</th>
                <td><a href="{% url 'list:detail' search.id  %}"><s>{{search.item}}</s></a></td>
                <td>{{search.category}}</td>
                <td>{{search.priority}}</td>
                <td><a href="{% url 'list:uncross' search.id  %}">сделано</a></td>
              </tr>
            {% else %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td><a href="{% url 'list:detail' search.id  %}">{{search.item}}</a></td>
              <td>{{search.category}}</td>
              <td>{{search.priority}}</td>
              <td><a href="{% url 'list:cross_off' search.id  %}">не сделано</a></td>
            </tr>
              
            {% endif %}

          {% endfor %}
        </tbody>
       
      </table>
      
    </div>
     
<!-- akhir list do -->

{% endblock content %}

todolist/list/templates/list/update.html
{% extends 'base.html' %}


{% block title %}
    {{Title}}
{% endblock title %}
    

{% block content %}

<div class="container pt-4">
    update
    <div>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{item_form}}
        </table>
        <button type="submit" class="btn btn-primary">Save</button>
        <hr>
    </div>

{% endblock content %}
    

todolist/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- CSS datatables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.22/datatables.min.css"/>

    <link rel="stylesheet" href="{% static 'mystyle.css' %}" type="text/css">
    
    <title>
        {% block title %}
            
        {% endblock title %}   
    </title>
  </head>
  <body>

<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home'  %}">to-do List</a>
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'list:index' %}">Список <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'list:create' %}">Настройки</a>
        </li>
      </ul>

    <!-- search -->
    <form action="{% url 'list:search' %}" method="GET" class="form-inline my-1 my-sm-0">
        <input class="form-control mr-sm-1" type="text" name='kolomCari' id="kolomcari" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-warning my-1 my-sm-0" type="submit">Search</button>
    </form>
    <!-- end search -->
    </div>
  </nav>
  <!-- end navbar -->

  <!--content  -->
<div class="container mt-5"> <!--wrap content-->
  <div class="row">

      {% block content %} 
    
      {% endblock content %}
   
</div>  <!--end row-->
</div> <!-- end wrap content-->
 <!--end content  -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

     <!-- javascript datatables -->
     <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.22/datatables.min.js"></script>

    <script>
      $(document).ready(function(){
          $('#example').DataTable();
      });
  </script>

  </body>
</html>

todolist/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {{Title}}
{% endblock title %}
  

{% block content %}

<!-- containts -->
    <div class="container mt-5">
    <!-- cov19 russia -->
      <div class="card text-center">
        <div class="card-header"  id="warna">
          {% for rusCov19 in case2 %}
          <h3>Случаи коронавируса в Российской Федерации</h3> <h5>({{rusCov19.CountryCode}}) <img width ="40px"src="{% static 'russia-flag.png' %}"></h5> 
        </div>
        <div class="card-body">
          
          <h5 class="card-title"> Новое подтверждено :  {{rusCov19.NewConfirmed}} </h5> 
          <h5 class="card-title"> Всего подтверждено :  {{rusCov19.TotalConfirmed}} </h5> 
          <h5 class="card-title"> Новых смертей :  {{rusCov19.NewDeaths}}  </h5>
          <h5 class="card-title"> Всего смертей :  {{rusCov19.TotalDeaths}} </h5> 
          <h5 class="card-title"> Новое Восстановленное :  {{rusCov19.NewRecovered}} </h5> 
          <h5 class="card-title"> Подтверждено новое общее восстановленных :  {{rusCov19.NewTotalRecoveredConfirmed}}  </h5>
          <!-- <h5 class="card-title"> Date :  {{rusCov19.Date}} </h5>  -->
          <p class="card-text"> </p>

          <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
        </div>
        <div class="card-footer text-muted" id="warna">
          источник : https://documenter.getpostman.com/  | Последнее обновление {{update}}
        </div>
        {% endfor %}
      </div>
      <!-- end cov19 russia -->

      <!-- cov19 tomsk -->
      {% for Cov19Tomsk in case3 %}
      <div class="card text-center mt-4">
        <div class="card-header" id="warna2">
          <h3>Случаи коронавируса в Томской области</h3> 
          <h6>({{Cov19Tomsk.isoCode}})<img width ="40px"src="{% static 'tomsk-flag.png' %}"></h6>
        </div>
        <div class="card-body">
          <h5 class="card-title">Зараженный: {{Cov19Tomsk.infected}} </h5>
          <h5 class="card-title">Восстановлен: {{Cov19Tomsk.recovered}}</h5>
          <h5 class="card-title">Умерший : {{Cov19Tomsk.deceased}}</h5>
          <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
          <a href="#region" class="btn btn-outline-primary">see all regions in Russia</a>
        </div>
        <div class="card-footer text-muted" id="warna2">
          источник : https://api.quarantine.country/api/v1/regions  | Последнее обновление {{update}}
        </div>
      </div>
      {% endfor %}
      <!-- end cov19 tomsk -->


      <!-- cov19 allregions -->
      <div id ="region" class="card text-center mt-4">
        <div class="card-header mb-1">
         <h3> CoronaVirus Cases stats in Russian Regions </h3>
        </div>
        <table id ="example"  class="table table-hover table-bordered table-sm">
          <thead>
            <tr>
              <th scope="col">No</th>
              <th scope="col">Region</th>
              <th scope="col">Total Confirmed</th>
              <th scope="col">Total Recovered</th>
              <th scope="col">Total Deaths</th>
            </tr>
          </thead>
          <tbody>
            {% for allRegion in case4 %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td class="text-left">{{allRegion.region}}</td>
              <td>{{allRegion.infected}}</td>
              <td>{{allRegion.recovered}}</td>
              <td>{{allRegion.deceased}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        <div class="card-footer text-muted">
          source : https://api.quarantine.country/api/v1/regions  | Last update {{update}}
        </div>
      </div>
      <!-- end cov19 allregions -->
</div>
<!-- end containts -->  
{% endblock content %}